Java solid kata solution
BAIRU-SHASHI-KANTH/task-list pull request #1
Opened 2023-03-06 07:31 UTC by BAIRU-SHASHI-KANTH

### Features Implemented : 

**Deadlines**

Give each task an optional deadline with the deadline <ID> <date> command.
Show all tasks due today with the today command.

**Views**
View tasks by deadline with the _view by deadline_ command.
Don’t remove the functionality that allows users to view tasks by project, but change the command to _view by project_.

2023-03-08 10:00 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ExecuteCommands.java
> +                break;
should not create instances for each execution call

2023-03-08 10:01 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddProject.java
> +    }
add interface and have taskList as class field and maintain a constructor

2023-03-08 10:01 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddTask.java
> +    public void add(String project, String description, TaskList taskList) {
add interface and have taskList as class field and maintain a constructor

2023-03-08 10:02 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskList.java
> +    public final Map<String, List<Task>> tasks = new LinkedHashMap<>();
this should not be public, we should encapsulate our code

2023-03-08 10:02 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskList.java
> +    public final PrintWriter out;
this should not be public, we should encapsulate our code

2023-03-08 10:03 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/DeleteTask.java
> +    public void delete(String idString, PrintWriter out, Map<String, List<Task>> tasks) {
add interface and have taskList as class field and maintain a constructor

2023-03-08 10:04 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ShowFactory.java
> +            default:
should not create instances for each call

2023-03-08 10:05 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ShowTaskWithDeadlines.java
> +    public void show(PrintWriter out, Map<String, List<Task>> tasks) {
have tasks as class field and maintain a constructor

2023-03-08 10:05 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ShowTasks.java
> +    public void show(PrintWriter out, Map<String, List<Task>> tasks) {
have tasks as class field and maintain a constructor

2023-03-08 10:05 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ShowTodayDeadlineTasks.java
> +        Date date = Calendar.getInstance().getTime();
have tasks as class field and maintain a constructor

2023-03-08 10:05 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskDeadline.java
> +public class TaskDeadline {
add interface and have tasks as class field and maintain a constructor

2023-03-08 10:06 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/TaskList.java
> +    public void add(String commandLine) {
have add method in different class

2023-03-08 10:06 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/UpdateTask.java
> +    public void setDone(String idString, boolean done, PrintWriter out,Map<String, List<Task>> tasks) {
add interface and have tasks as class field and maintain a constructor

2023-03-08 10:06 UTC, AbhilashZemoso requested changes
work on comments
make sure all OOPS principles are also followed

2023-03-08 11:43 UTC, BAIRU-SHASHI-KANTH commented
> work on comments make sure all OOPS principles are also followed

implemented the requested changes

2023-03-09 05:48 UTC, AbhilashZemoso approved these changes
LGTM

2023-03-09 06:04 UTC, merged